### ISSUE TITLE
Environment set in cmake-variants.yaml are not applied

### ISSUE THREAD

**Issue by hunger** [microsoft/vscode-cmake-tools#1121]
environment variables set in `cmake-variants.yaml` are ignored

I set up a `cmake-variants.yaml` file with the following variant:
```
qt:
  default: noqt
  choices:
    qt5:
      short: Qt 5
      long: Provide Qt 5 configuration to CMake
      setting:
        env:
          Qt5_DIR: /home/Qt/latest/gcc_64/lib/cmake/Qt5
          Qt6_DIR: Qt6_DIR-NOTFOUND
    qt6:
      short: Qt 6
      long: Provide Qt 6 configuration to CMake
      setting:
        env:
          Qt5_DIR: Qt5_DIR-NOTFOUND
          Qt6_DIR: /home/Qt/latest/gcc_64/lib/cmake/Qt6
    noqt:
      short: no Qt
      long: Do not provide Qt configuration to CMake
      setting:
        env:
          Qt5_DIR: Qt5_DIR-NOTFOUND
          Qt6_DIR: Qt6_DIR-NOTFOUND
```

This does not work as expected.

The environment seen by cmake does not contain either of the two environment variables.

### Expected:

The two environment variables are seen by CMake.

1. Add the yaml-snippet from above to your variants
2. Make CMake print the two environment variables
3. Select this variant and check the output from CMake

### Apparent Behavior:

CMake does not see any of the two variables as set.

I am skipping the CMake Tools Log since there is nothing relevant in it AFAICT.

```
<No idea how to get the developer tools log, sorry>
```

### Platform and Versions

- **Operating System**: Arch Linux
- **CMake Version**: 
- **VSCode Version**: 1.43.0
- **CMake Tools Extension Version**: 1.3.1
- **Compiler/Toolchain**: Clang 9.0

### Notes:

I connect with my VSCode into a container via SSH and run cmake/ninja/... all inside that container.

**Comment by bobbrow** [comment]
I'm seeing this failing in the CI tests over the weekend.  I don't know where this is coming from yet, but I'm investigating...

**Comment by bobbrow** [comment]
Your issue seems unrelated to the CI build issue.  I should have looked more closely at your syntax.  `setting` is not a valid keyword and `env` is not a child of that.  Try this:

```
qt:
  default: noqt
  choices:
    qt5:
      short: Qt 5
      long: Provide Qt 5 configuration to CMake
      env:
        Qt5_DIR: /home/Qt/latest/gcc_64/lib/cmake/Qt5
        Qt6_DIR: Qt6_DIR-NOTFOUND
    qt6:
      short: Qt 6
      long: Provide Qt 6 configuration to CMake
      env:
        Qt5_DIR: Qt5_DIR-NOTFOUND
        Qt6_DIR: /home/Qt/latest/gcc_64/lib/cmake/Qt6
    noqt:
      short: no Qt
      long: Do not provide Qt configuration to CMake
      env:
        Qt5_DIR: Qt5_DIR-NOTFOUND
        Qt6_DIR: Qt6_DIR-NOTFOUND
```
