### ISSUE TITLE
[question/bug] cmake-variants.yaml notpassing variable to cmake cache

### ISSUE THREAD

**Issue by atsju** [microsoft/vscode-cmake-tools#729]
### Brief Issue Summary

cmake-variants.yaml
```
FW_VARIANT:
  default: FIRMWARE_1
  choices:
    'FIRMWARE_1':
      short: "fw1"
      long: "firmware 1"
      settings:
        FW_VARIANT: FIRMWARE_1
    'FIRMWARE_2':
      short: "fw2"
      long: "firmware 2"
      setting:
        FW_VARIANT: FIRMWARE_2
```

cmakelist.txt

```
set(FW_VARIANT "FIRMWARE_1" CACHE STRING "desired firmware")
message("FW is ${FW_VARIANT}")
```

I have 2 variants and  it seems the FW_VARIANT is never passed to cmake to update the cache.

### Expected:

I expect a cmakecache update FW_VARIANT variable when selecting the corresponding variant.
The file is not updated even when re-runing generation I am not able to get the variable updated (or even set if not created in cmakelist).

Searching on github I did not found any project using cmake-variants.yaml. Could you provide an example project based on this [doc](https://vector-of-bool.github.io/docs/vscode-cmake-tools/variants.html) ?

### Platform and Versions

- **Operating System**:Windows 10
- **CMake Version**: 3.15.0
- **VSCode Version**: 1.37.0
- **CMake Tools Extension Version**: 1.1.3
- **Compiler/Toolchain**: GCC

**Comment by Randshot** [comment]
Hey, I have tried to replicate your issue, but it seemed to work just fine for me.
I used the following `cmake-variants.yaml`:
```yaml
buildType:
  default: debug
  description: build type
  choices:
    debug:
      short: debug
      buildType: RelWithDebInfo
      settings:
        TEST_SETTING: test_1
    release:
      short: release
      buildType: Release
      settings:
        TEST_SETTING: test_2

```
And this in the `CMakeListst.txt`:
```cmake
set(TEST_SETTING "test_0" CACHE STRING "test setting")
message(STATUS "  TEST_SETTING:             ${TEST_SETTING}")
```
The output for debug and release respectively were:
```
[cmake]   TEST_SETTING:             test_1
[cmake]   TEST_SETTING:             test_2
```
