### ISSUE TITLE
Greater control over variable substitution 

### ISSUE THREAD

**Issue by skebanga** [microsoft/vscode-cmake-tools#852]
### Brief Issue Summary

Perhaps this is already possible, but I have been unable to figure it out.

I would like to be able to have finer grained control over variable substitution

### Expected:

Unfortunately some external tools expect `${buildType}` to be lower case `debug`/`release`, whereas the variable substituted is `Debug`/`Release`.

### Configuration:

My `.vscode/settings.json` file:

```json
{
    "cmake.buildDirectory": "${workspaceRoot}/.build/${buildType}",
}
```

My `.vscode/cmake-variants.yaml` file:

```yaml
 buildType:
  default: debug
  choices:
    debug:
      short: Debug
      long: Emit debug information
      buildType: Debug
    release:
      short: Release
      long: Optimize generated code
      buildType: Release
```

Is there a way to substitute `debug` instead of `Debug` in my `cmake.buildDirectory` value?

### Platform and Versions

- **Operating System**: Ubuntu
- **CMake Version**: 3.10.2
- **VSCode Version**: 1.39.2
- **CMake Tools Extension Version**: 1.1.3
- **Compiler/Toolchain**: gcc-7.4

**Comment by skebanga** [comment]
I tried using `${variant:SHORT}` and `${variant:short}` in my `cmake.buildDirectory`, but that expanded to an empty string

**Comment by skebanga** [comment]
Aha! Figured it out!

By using `${variant:buildType}`, and changing `cmake-variants.yaml` to have lower case in the `short` options, I managed to get my desired lower case build variant.

So to add the specifics:

My `.vscode/settings.json` file:

```json
{
    "cmake.buildDirectory": "${workspaceRoot}/.build/${variant:buildType}",
}
```

My `.vscode/cmake-variants.yaml` file:

```yaml
 buildType:
  default: debug
  choices:
    debug:
      short: debug
      long: Emit debug information
      buildType: Debug
    release:
      short: release
      long: Optimize generated code
      buildType: Release
```
